
# files will be symlinked from VALUE to annotation/KEY
# e.g. from /path/to/genome.fa to annotation/genome.fa
annotation: 
  genome.fa: /path/to/genome.fa
  genes.gtf: /path/to/genes.gtf
  transcriptome.gtf: /path/to/transcriptome.gtf
  genome.chrom.sizes: /path/to/genome.chrom.sizes
  sqanti.polya.list: /path/to/sqanti.polya.list
  splice_junctions_filtered.tab: /path/to/splice_junctions_filtered.tab
  promoter.db.edp.bed: db/promoter.db.edp.bed
  combined.rds.clusters.new.gff: db/combined.rds.clusters.new.gff

sample_types:
  - ont-cdna
  - ont-direct
  - flam-seq
  - iso-seq

params:
  flair_collapse_edp_tss:
    ont-cdna: "--max_ends 5 -s 3"
    ont-direct: "--max_ends 5 -s 2"
    flam-seq: "--max_ends 5 -s 2"
    iso-seq: "--max_ends 5 -s 2"

mapper:
  flam-seq: starlong
  iso-seq: starlong
  ont-cdna: minimap2
  ont-direct: minimap2
